---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smbcreds
  namespace: default
spec:
  encryptedData:
    password: AgBKRVNY4dPUj5OeWmIHRySgkme9t+RhvbS0X0pZnYTSy2zB1+vaxIAr9cWQGfflyQGvLAB02wGZJ50HS3BxR5AOwhbUViH/8Dlno8dx7pkD8iRIH3YPASLRRhOiQPksUi1UfN5KkfB7rFaV08yaRvIZ1BBsVd//XcGFk8hHaNFx99+MjKAiN5mzgJUYOXBJaHW5Q6d6u6m0vwYYijWP9VH+hf5+h7nFrpYRtK1ycEGHgrCLvffPFWaEGHBUndSDcf1nCA30jN+ltDt0twXMf8v2PjS/L54AjLF5eqtk77nI+VeO45YI2EZLItwv8CuBKj7/ujnX22Ty/8dA0f49vczVDtt7Pcji857FSMwXGU9NEzZNZN53KQlIl4aCf8oO/UlSLgOwnXZ89RVtuLG7aNLkp9zpo0XAzXdYFzDWb04cHJGGFQ6C4L8XxGLSwwptoLttnB7Tge/qMrP188Qd86l3n1Am4Wc04fafIiZA9SbKt23mI6fA6dMYO9xQ5bpH4gRyeWWeCwb7h46KhZ435ngXPxp/pNz7nCggjrkUNeimj1pMwxxmDNlP9Pg0fKVtn7xKgedTIuXr3Z+n1t/SuN3IF8RhGJZmY2YQusyupFZ61ZrsiLITJkt11u+wa9jmfVpVj0I4/ULlnLX96G1WZ4sD7Z9PEVfx5w1eS8ICCzRTk158kQ4/RyQLJqOHSgauNhU52NJE41XNtKsRqg==
    username: AgCQqpLEL2QKs7ZiE9FN7ir8V8PNK8FvmwaFnGlValPBQE1gqS8M2yTDE67nI+14URCTAYKq07GEQTatAiIO7X1U9tMScy9Z97WqMONMYw8cSo0ewUQQwg6grvWd9/xCZbThL/7sw/lKOFaoqB60Z9jXrK5lC9nyEunlRuAihXYJmRwUUPtyMbbE1icK0+foDYIXxUwNi+wKntuvdi0UHOkUDTC0Mt2FRVQ5H8yrQVCHXSIexCZtHZy2z5UjJj3LhOshLLaqFTfCQGI8yyqZkv23tERDFgqZpPJUg8gVhUdtYPe6GBoQ4nD2RPs1jctpa+YKATaXOAs4wzsxdYG+ABeFZ8yiJaAYBb07OQSVsJV25VP1U09T2/TtVvq9sxHab5Ssk1CsUyAboIaALskL6P0BB+SCBgpp1XP9J1PhoN3b2v5RDikSUWBIH1i1eYZlToPMVt1/OldZZweBjryZdmlF6zao2DiR6Gj5UgSqk/ivs3pmYSrbwDtSVJ6ATWdTSYtShHGW+GsPV/JKA+0rOVuwC+96mcct72F2jyBZ6YaJHkDrA2cQOBhZ4PIjUKAHw0m5cWb7E23Nej27pbmdPypgVjRVe5gZCHRCJOVPZIOH0EuObGoDd8GXcZ68Aa6/3GbHGxvP2JX7YrBmyWapuwIPc2kdCiJD4TSRqpAOH5vYUVF81S9gnhSMHtQnCY1fXPjIYe5OifM2SQ/KhdDEc9YfsGf8TRA=
  template:
    metadata:
      creationTimestamp: null
      name: smbcreds
      namespace: default
